REM I don't know batch script at all, this is generated by chatgpt from gen_trait.sh. Please send help.

@echo off

setlocal

set "folder=%~1"
setlocal enabledelayedexpansion

if "%folder%"=="" (
  set "wd=%cd%\json"
) else (
  set "wd=%folder%"
)
set "out_dir=%~dp0generated"

if not exist "%out_dir%" mkdir "%out_dir%"

for %%E in (trait json) do (
  for %%F in ("%wd%\*.%%E") do (
    set "filename=%%~nxF"
    if not "!filename!"=="gen_trait.schema.json" (
      python -m gen_trait "%%~F" > "%out_dir%\%%~nF.hpp"
    )
  )
)

where clang-format >nul 2>&1
if !errorlevel! equ 0 (
  for %%F in ("%out_dir%\*.hpp") do (
    clang-format -i "%%~F"
  )
) else (
  echo clang-format not found, skip formatting
)

endlocal
