REM I don't know batch script at all, this is generated by chatgpt from gen_trait.sh. Please send help.

@echo off

setlocal

set "folder=%~1"
setlocal enabledelayedexpansion

if "%folder%"=="" (
  set "wd=%cd%"
) else (
  set "wd=%folder%"
)
set "py=%~dp0gen_trait.py"

for %%F in ("%wd%\*.json") do (
  set "filename=%%~nxF"
  if not "!filename!"=="gen_trait.schema.json" (
    python "%py%" "%%~F" > "%wd%\!filename:.json=.hpp!"
  )
)

where clang-format >nul 2>&1
if !errorlevel! equ 0 (
  for %%F in ("%wd%\*.hpp") do (
    clang-format -i "%%~F"
  )
) else (
  echo clang-format not found, skip formatting
)

endlocal

